meta_product_name: "Blanck Mass"
meta_title: "Product name - Product tagline"
meta_description: "Blanck Mass - Official website of Blanck Mass"
meta_image: "full_logo_shadow.png" # should exist in `app/assets/images/`
twitter_account: "@BlanckMass"   # required for Twitter Cards
