meta_product_name: "Blanck Mass"
meta_title: "Blanck Mass - Official website"
meta_description: "Blanck Mass - Official website"
meta_image: "facebook_link.png" # should exist in `app/assets/images/`
twitter_account: "@BlanckMass"   # required for Twitter Cards
